/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BeginnerRouteImport } from './routes/beginner'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as GroceryListRouteImport } from './routes/grocery-list'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCommentsRouteImport } from './routes/admin.comments'
import { Route as AdminCuisinesRouteImport } from './routes/admin.cuisines'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminRecipesRouteImport } from './routes/admin.recipes'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CuisinesIndexRouteImport } from './routes/cuisines.index'
import { Route as CuisinesSlugRouteImport } from './routes/cuisines.$slug'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as RecipesSlugRouteImport } from './routes/recipes.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BeginnerRoute = BeginnerRouteImport.update({
  id: '/beginner',
  path: '/beginner',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceryListRoute = GroceryListRouteImport.update({
  id: '/grocery-list',
  path: '/grocery-list',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCuisinesRoute = AdminCuisinesRouteImport.update({
  id: '/cuisines',
  path: '/cuisines',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecipesRoute = AdminRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const CuisinesIndexRoute = CuisinesIndexRouteImport.update({
  id: '/cuisines/',
  path: '/cuisines/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuisinesSlugRoute = CuisinesSlugRouteImport.update({
  id: '/cuisines/$slug',
  path: '/cuisines/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesSlugRoute = RecipesSlugRouteImport.update({
  id: '/recipes/$slug',
  path: '/recipes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/beginner': typeof BeginnerRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/grocery-list': typeof GroceryListRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/cuisines': typeof AdminCuisinesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/recipes': typeof AdminRecipesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/cuisines/$slug': typeof CuisinesSlugRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/cuisines/': typeof CuisinesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beginner': typeof BeginnerRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/grocery-list': typeof GroceryListRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/cuisines': typeof AdminCuisinesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/recipes': typeof AdminRecipesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/cuisines/$slug': typeof CuisinesSlugRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/cuisines': typeof CuisinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/beginner': typeof BeginnerRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/grocery-list': typeof GroceryListRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/cuisines': typeof AdminCuisinesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/recipes': typeof AdminRecipesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/cuisines/$slug': typeof CuisinesSlugRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/cuisines/': typeof CuisinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/beginner'
    | '/create'
    | '/explore'
    | '/feed'
    | '/grocery-list'
    | '/login'
    | '/notifications'
    | '/register'
    | '/admin/comments'
    | '/admin/cuisines'
    | '/admin/posts'
    | '/admin/recipes'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/cuisines/$slug'
    | '/profile/$username'
    | '/recipes/$slug'
    | '/admin/'
    | '/cuisines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beginner'
    | '/create'
    | '/explore'
    | '/feed'
    | '/grocery-list'
    | '/login'
    | '/notifications'
    | '/register'
    | '/admin/comments'
    | '/admin/cuisines'
    | '/admin/posts'
    | '/admin/recipes'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/cuisines/$slug'
    | '/profile/$username'
    | '/recipes/$slug'
    | '/admin'
    | '/cuisines'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/beginner'
    | '/create'
    | '/explore'
    | '/feed'
    | '/grocery-list'
    | '/login'
    | '/notifications'
    | '/register'
    | '/admin/comments'
    | '/admin/cuisines'
    | '/admin/posts'
    | '/admin/recipes'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/cuisines/$slug'
    | '/profile/$username'
    | '/recipes/$slug'
    | '/admin/'
    | '/cuisines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BeginnerRoute: typeof BeginnerRoute
  CreateRoute: typeof CreateRoute
  ExploreRoute: typeof ExploreRoute
  FeedRoute: typeof FeedRoute
  GroceryListRoute: typeof GroceryListRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  RegisterRoute: typeof RegisterRoute
  CuisinesSlugRoute: typeof CuisinesSlugRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  RecipesSlugRoute: typeof RecipesSlugRoute
  CuisinesIndexRoute: typeof CuisinesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beginner': {
      id: '/beginner'
      path: '/beginner'
      fullPath: '/beginner'
      preLoaderRoute: typeof BeginnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grocery-list': {
      id: '/grocery-list'
      path: '/grocery-list'
      fullPath: '/grocery-list'
      preLoaderRoute: typeof GroceryListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cuisines': {
      id: '/admin/cuisines'
      path: '/cuisines'
      fullPath: '/admin/cuisines'
      preLoaderRoute: typeof AdminCuisinesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recipes': {
      id: '/admin/recipes'
      path: '/recipes'
      fullPath: '/admin/recipes'
      preLoaderRoute: typeof AdminRecipesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/cuisines/': {
      id: '/cuisines/'
      path: '/cuisines'
      fullPath: '/cuisines/'
      preLoaderRoute: typeof CuisinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuisines/$slug': {
      id: '/cuisines/$slug'
      path: '/cuisines/$slug'
      fullPath: '/cuisines/$slug'
      preLoaderRoute: typeof CuisinesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$slug': {
      id: '/recipes/$slug'
      path: '/recipes/$slug'
      fullPath: '/recipes/$slug'
      preLoaderRoute: typeof RecipesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminCuisinesRoute: typeof AdminCuisinesRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminRecipesRoute: typeof AdminRecipesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCommentsRoute: AdminCommentsRoute,
  AdminCuisinesRoute: AdminCuisinesRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminRecipesRoute: AdminRecipesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BeginnerRoute: BeginnerRoute,
  CreateRoute: CreateRoute,
  ExploreRoute: ExploreRoute,
  FeedRoute: FeedRoute,
  GroceryListRoute: GroceryListRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  RegisterRoute: RegisterRoute,
  CuisinesSlugRoute: CuisinesSlugRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  RecipesSlugRoute: RecipesSlugRoute,
  CuisinesIndexRoute: CuisinesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
